### PR TITLE
Implement ESIOS API Token support

### LINKED ISSUE #9: Price list for energy injected on the grid when solar installations
Hi,

Is it possible to add the hourly price for the energy injected on the grid aswell? (https://www.esios.ree.es/es/analisis/1739?vis=1&start_date=16-01-2021T00%3A00&end_date=16-01-2021T23%3A00&compare_start_date=15-01-2021T00%3A00&groupby=hour&compare_indicators=1013,1014,1015)

This would be awesome

### PR DESCRIPTION
**Pull request by azogue**
- ✨ Implement **support to access the extended ESIOS API** with a personal token
(you must request yours by mailing to [consultasios@ree.es](mailto:consultasios@ree.es?subject=Personal%20token%20request)), with initial support for the existent PVPC price sensor (ESIOS indicator code: **1001**), and **3 new ones** 🤩:
  * **Inyection price** sensor (ESIOS indicator code: **1739**), name: "Precio de la energía excedentaria del autoconsumo para el mecanismo de compensación simplificada"
  * **MAG price** sensor (ESIOS indicator code: **1900**), name: "Desglose peaje por defecto 2.0TD excedente o déficit de la liquidación del mecanismo de ajuste de costes de producción"
  * **OMIE price** sensor (ESIOS indicator code: **10211**), name: "Precio medio horario final suma de componentes"

- 💥 Remove 'apidatos' support as alternative _data-source_, leaving only public and private paths for https://api.esios.ree.es

- ✨ Signal bad auth for esios token calls with a custom exception, to handle 'reauth' flow in Home-Assistant

- ✨ Add helper methods for HA integration to manage unique ids for each sensor, to update the enabled sensors to download, and to check the API token

- ♻️ Use dataclasses for `EsiosApiData` and `EsiosResponse` data containers, instead of typed dicts

- ✅ tests: Update fixtures for esios sensors and adapt tests to the new interface and the multiple-sensors behaviour

- 📦️ Bump mayor version to **v4** and lighten dev-env, removing pre-commit related modules and adding python-dotenv

closes #9 #45

### CODE REVIEW

**Comment by EddieKnight1** [comment]
Sorry @azogue if I'm posting this in the wrong place.

How do I add this new version to HA? Is it already available as an integration? or should I download it from somewhere else and place it in the custom_components folder?

**Comment by azogue** [comment]
> Sorry @azogue if I'm posting this in the wrong place.
> 
> How do I add this new version to HA? Is it already available as an integration? or should I download it from somewhere else and place it in the custom_components folder?

I have to make a PR in ha-core, and another one in the ha-docs. Then goes the review process, and after the merge, these kind of changes are published in the monthly releases. I'll try to make it for v2023.2.0 🤞, but I'm not sure it will be on time 😰

In the meanwhile, for **beta-testing** it, you may copy and decompress this **[pvpc_hourly_pricing.zip](https://github.com/azogue/aiopvpc/files/10380828/pvpc_hourly_pricing.zip)** into your `config/custom_components`, to swap the official integration for the new one to come. After release, just remove it 👍

**Comment by enredador** [comment]
Thank you for the new version @azogue. I have installed it successfully (I will report any other issues). I see that the hourly prizes (current and next day) included in the sensors as attributes are  now rendered in €/Mwh whereas the sensor value and some other attributes are in €/Kwh.

**Comment by azogue** [comment]
> I see that the hourly prizes (current and next day) included in the sensors as attributes are now rendered in €/Mwh whereas the sensor value and some other attributes are in €/Kwh.

Hi @enredador,  **that was an error** 🙈

When developing it, I saw that the new HA frontend renders numeric attributes for entities with 2 decimals max, so for most sensors with values < 100 €/MWh, the price attributes appeared as `0,00` 😢

As I was not sure if it was _my fault_, I changed them to €/MWh, and then I forgot about them 😱

I'll revert it with a new version patch with the fix 🚀

**Comment by azogue** [comment]
The zip package is updated to point to `"requirements": ["aiopvpc==4.0.1"]` in the `manifest.json` (it's the only change, if already downloaded, just edit yours)

**Comment by enredador** [comment]
Thank you @azogue. I made the changes and it is running ok now. May be using €-cents/kWh as unit would have been a more readable choice.

**Comment by jlopez77** [comment]
This V4.0.1 works fine with the API token. I still can't see surplus (injection) prices, am I doing something wrong?

**Comment by azogue** [comment]
> This V4.0.1 works fine with the API token. I still can't see surplus (injection) prices, am I doing something wrong?

Hi!

I just published, as a new repository, the 'custom' version of the official component, to replace directly the one included in HA, with the pending changes since January 🐢

It is here: https://github.com/azogue/ha-pvpc-custom

And it is compatible with HACS, adding that link as 'custom repository' with 'category' "Integration" 👍

I recommend everyone to install this new custom component and remove all those components downloaded in some zip (including that 'esios').

**Pull request merged**
